/**
 * Solidity ⇄ TypeScript differential test — the PLAN-02 gate.
 *
 * The corpus is regenerated by `forge test --match-test test_writeCorpus`; this
 * suite recomputes every row independently and asserts bit-identity. It is a
 * differential test rather than a golden-file test on purpose: a change on either
 * side that the other does not follow fails here.
 *
 * The stake is that `planId` cannot be fixed after the fact. A borrower's
 * authorizations name a payee derived from it, so a divergence between the
 * contract and the SDK is not a bug to patch — it is a migration of every
 * outstanding strip, discovered when the first collection fails.
 */
import {existsSync, readFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";
import {describe, expect, it} from "vitest";
import {getAddress, type Address, type Hex} from "viem";

import {
  checkNonce,
  checkNonces,
  cloneInitCodeHash,
  derivePlan,
  derivePlanId,
  ERC1167_CREATION_PREFIX,
  ERC1167_RUNTIME_SUFFIX,
  PLAN_ID_TYPEHASH,
  predictPlanAddress,
  type PlanTerms,
} from "../src/plan-id.js";

interface CorpusRow {
  chainId: string;
  factory: Address;
  implementation: Address;
  borrower: Address;
  merchant: Address;
  token: Address;
  principal: string;
  installmentCount: string;
  firstDueDate: string;
  interval: string;
  originationNonce: string;
  termsHash: Hex;
  planId: Hex;
  predictedAddress: Address;
  nonces: Hex[];
}

interface Corpus {
  planIdTypehash: Hex;
  erc1167CreationPrefix: Hex;
  erc1167RuntimeSuffix: Hex;
  rows: CorpusRow[];
}

const CORPUS_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "contracts",
  "corpus",
  "plan-id.json",
);

function loadCorpus(): Corpus {
  if (!existsSync(CORPUS_PATH)) {
    throw new Error(
      `No corpus at ${CORPUS_PATH}.\n\n` +
        "Generate it from the Solidity side first:\n" +
        "  forge test --root contracts --match-test test_writeCorpus\n\n" +
        "This test is meaningless without it — it would be asserting that TypeScript\n" +
        "agrees with itself.",
    );
  }
  return JSON.parse(readFileSync(CORPUS_PATH, "utf8")) as Corpus;
}

function toTerms(row: CorpusRow): PlanTerms {
  return {
    chainId: BigInt(row.chainId),
    factory: row.factory,
    implementation: row.implementation,
    borrower: row.borrower,
    merchant: row.merchant,
    token: row.token,
    principal: BigInt(row.principal),
    installmentCount: BigInt(row.installmentCount),
    firstDueDate: BigInt(row.firstDueDate),
    interval: BigInt(row.interval),
    originationNonce: BigInt(row.originationNonce),
    termsHash: row.termsHash,
  };
}

const corpus = loadCorpus();

describe("constants agree across implementations", () => {
  it("plan typehash", () => {
    expect(PLAN_ID_TYPEHASH).toBe(corpus.planIdTypehash);
  });

  it("EIP-1167 creation prefix", () => {
    expect(ERC1167_CREATION_PREFIX.toLowerCase()).toBe(corpus.erc1167CreationPrefix.toLowerCase());
  });

  it("EIP-1167 runtime suffix", () => {
    expect(ERC1167_RUNTIME_SUFFIX.toLowerCase()).toBe(corpus.erc1167RuntimeSuffix.toLowerCase());
  });
});

describe(`differential corpus (${corpus.rows.length} rows)`, () => {
  it("is large enough to be worth running", () => {
    expect(corpus.rows.length).toBeGreaterThanOrEqual(100);
  });

  it.each(corpus.rows.map((row, i) => [i, row] as const))("row %i — planId", (_i, row) => {
    expect(derivePlanId(toTerms(row))).toBe(row.planId);
  });

  it.each(corpus.rows.map((row, i) => [i, row] as const))("row %i — clone address", (_i, row) => {
    const predicted = predictPlanAddress({
      deployer: row.factory,
      implementation: row.implementation,
      planId: row.planId,
    });
    expect(predicted).toBe(getAddress(row.predictedAddress));
  });

  it.each(corpus.rows.map((row, i) => [i, row] as const))("row %i — every nonce", (_i, row) => {
    const nonces = checkNonces(row.planId, row.installmentCount);
    expect(nonces).toHaveLength(row.nonces.length);
    expect(nonces).toEqual(row.nonces);
  });

  it.each(corpus.rows.map((row, i) => [i, row] as const))(
    "row %i — derivePlan composes to the same result",
    (_i, row) => {
      const derived = derivePlan(toTerms(row));
      expect(derived.planId).toBe(row.planId);
      expect(derived.address).toBe(getAddress(row.predictedAddress));
      expect(derived.nonces).toEqual(row.nonces);
    },
  );
});

describe("properties the corpus cannot exhaust", () => {
  const base = toTerms(corpus.rows[0]!);

  it("changing any single field changes the plan id", () => {
    const mutations: Array<[string, PlanTerms]> = [
      ["chainId", {...base, chainId: base.chainId + 1n}],
      ["factory", {...base, factory: "0x000000000000000000000000000000000000dEaD"}],
      ["implementation", {...base, implementation: "0x000000000000000000000000000000000000dEaD"}],
      ["borrower", {...base, borrower: "0x000000000000000000000000000000000000dEaD"}],
      ["merchant", {...base, merchant: "0x000000000000000000000000000000000000dEaD"}],
      ["token", {...base, token: "0x000000000000000000000000000000000000dEaD"}],
      ["principal", {...base, principal: BigInt(base.principal) + 1n}],
      ["installmentCount", {...base, installmentCount: base.installmentCount + 1n}],
      ["firstDueDate", {...base, firstDueDate: base.firstDueDate + 1n}],
      ["interval", {...base, interval: base.interval + 1n}],
      ["originationNonce", {...base, originationNonce: base.originationNonce + 1n}],
      ["termsHash", {...base, termsHash: `0x${"11".repeat(32)}` as Hex}],
    ];

    const baseId = derivePlanId(base);
    for (const [field, mutated] of mutations) {
      expect(derivePlanId(mutated), `mutating ${field} did not change the plan id`).not.toBe(baseId);
    }
  });

  it("origination nonce separates two identical purchases", () => {
    const first = derivePlan(base);
    const second = derivePlan({...base, originationNonce: base.originationNonce + 1n});

    expect(second.planId).not.toBe(first.planId);
    expect(second.address).not.toBe(first.address);
    // The consequential half: a burned check nonce from the first attempt must not
    // make the second plan unsignable.
    expect(second.nonces[0]).not.toBe(first.nonces[0]);
  });

  it("a new implementation vintage produces a different identity", () => {
    const next = derivePlan({
      ...base,
      implementation: "0x00000000000000000000000000000000DeaDBeef",
    });
    expect(next.planId).not.toBe(derivePlanId(base));
  });

  it("nonces never collide within a plan", () => {
    const nonces = checkNonces(corpus.rows[0]!.planId, 64);
    expect(new Set(nonces).size).toBe(64);
  });

  it("nonces never collide across plans at the same index", () => {
    const seen = new Set<Hex>();
    for (const row of corpus.rows) {
      const nonce = checkNonce(row.planId, 0);
      expect(seen.has(nonce), `index-0 nonce collided across plans: ${nonce}`).toBe(false);
      seen.add(nonce);
    }
  });

  it("init code hash depends only on the implementation", () => {
    const a = cloneInitCodeHash(base.implementation);
    const b = cloneInitCodeHash(base.implementation);
    const c = cloneInitCodeHash("0x000000000000000000000000000000000000dEaD");
    expect(a).toBe(b);
    expect(a).not.toBe(c);
  });

  it("address prediction is deployer-scoped", () => {
    const fromFactory = predictPlanAddress({
      deployer: base.factory,
      implementation: base.implementation,
      planId: corpus.rows[0]!.planId,
    });
    // The shared permissionless CREATE2 deployer, which plans deliberately avoid.
    const fromSharedDeployer = predictPlanAddress({
      deployer: "0x4e59b44847b379578588920cA78FbF26c0B4956C",
      implementation: base.implementation,
      planId: corpus.rows[0]!.planId,
    });
    expect(fromFactory).not.toBe(fromSharedDeployer);
  });

  it("accepts checksummed and lowercase addresses identically", () => {
    const lower = {
      ...base,
      borrower: base.borrower.toLowerCase() as Address,
      factory: base.factory.toLowerCase() as Address,
    };
    expect(derivePlanId(lower)).toBe(derivePlanId(base));
  });
});
